name:                bank-kata-with-haskell
version:             0.1.0.0
github:              "githubuser/bank-kata-with-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/albertllousas/bank-kata-with-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.9.3

library:
  source-dirs: src

tests:
  bank-kata-with-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bank-kata-with-haskell
    - hspec
    - HUnit
    - main-tester
    - bytestring
    - utf8-string
